import XCTest
import UniformTypeIdentifiers
@testable import LocalGallery

/// Pins the metadata reader's output over the adversarial asset tree in
/// `core/fixtures/scan-conformance/assets/`.
///
/// Generated from the shipping Swift `MetadataReader`; now run against the Rust
/// `gallery-meta` read side through the FFI, with **every assertion and every
/// note unchanged**. `core/gallery-meta/tests/metadata_conformance.rs` checks
/// the same file on the host; this one checks that the *bridge* — the
/// device-zone resolution of the core's zone-less wall clock, the Unix-seconds
/// video date — lands on the same values the Swift reader produced.
///
/// The `notes` on each entry are part of the fixture on purpose — they are the
/// only place several of these behaviours are written down.
///
/// Assets are built by `scripts/gen_conformance_assets.py`; the expectation
/// file is regenerated by running this suite with `CONFORMANCE_REGEN=1`.
final class MetadataConformanceTests: XCTestCase {

    // MARK: - Fixture shape

    struct Dump: Codable, Equatable {
        /// Bump when the *shape* of an entry changes (not when a value moves).
        let schema: Int
        let files: [Entry]
    }

    struct Entry: Codable, Equatable {
        /// Path relative to `assets/`, `/`-separated. Sorted, so the file is
        /// stable regardless of directory-enumeration order.
        let path: String
        /// How the scan pipeline classifies the file by extension:
        /// `image` / `video` / `skipped` (the scanner never opens the last).
        let scannerKind: String
        /// A `<name>.xmp` sits next to it.
        let hasSidecar: Bool
        /// `readImageMetadata` — run for every entry including
        /// videos and `skipped` files, to pin what the reader *would* return.
        let dateTaken: ConformanceDate?
        let countryCode: String?
        let gpsLatitude: Double?
        let gpsLongitude: Double?
        let hierarchicalTags: [ConformanceTag]
        let faceRegions: [ConformanceRegion]
        /// `readVideoDate` — run only for `video` entries.
        let videoDate: ConformanceDate?
        /// Behaviour this entry exists to pin. Asserted like everything else.
        let notes: [String]
    }

    // MARK: - Annotations
    //
    // Keyed by the relative asset path. Every landmine the port could step on
    // is spelled out here rather than in a comment that only this file sees.

    private static let notes: [String: [String]] = [
        // --- EXIF dates -----------------------------------------------------
        "exif/full.jpg": [
            "Date order is DateTimeOriginal → DateTimeDigitized → TIFF DateTime.",
            "SubSecTimeOriginal (250) and OffsetTimeOriginal (+02:00) are DROPPED: the format string is exactly \"yyyy:MM:dd HH:mm:ss\" and neither field is consulted. Subsecond is always .000.",
            "Orientation is not read by the app at all — the core parses it for its own decode path and the app never asks for it.",
        ],
        "exif/digitized_only.jpg": ["Falls through to DateTimeDigitized when DateTimeOriginal is absent."],
        "exif/tiff_datetime_only.jpg": ["Falls through to TIFF:DateTime (exiftool ModifyDate) when both EXIF dates are absent."],
        "exif/zero_date.jpg": [
            "The \"0000:00:00 00:00:00\" camera sentinel is REJECTED by the non-lenient formatter (month 00 is out of range), so the walk falls through to DateTimeDigitized.",
            "A chrono parser that accepts month 0 / day 0 would diverge here.",
        ],
        "exif/hour_24.jpg": [
            "LANDMINE: hour 24 is ACCEPTED and rolls into the next day — 2021:07:04 24:00:00 becomes 2021-07-05T00:00:00.",
            "So the parser is strict about out-of-range months/days but lenient about hour 24. A naive strict `%H` (0..=23) parse in Rust would return nil instead.",
        ],
        "exif/impossible_date.jpg": ["Month 13 / day 45 is rejected by the non-lenient parser, so DateTimeDigitized wins."],
        "exif/none.jpg": ["No EXIF, no XMP, no sidecar: every field nil/empty."],

        // --- GPS ------------------------------------------------------------
        "gps/north_east.jpg": ["GPSAltitude / GPSAltitudeRef are read by nobody — the reader has no altitude field."],
        "gps/south_west.jpg": [
            "Ref \"S\"/\"W\" negate the (always positive) magnitudes.",
            "GPSAltitudeRef=1 (below sea level) is ignored along with the altitude.",
            "SUB-ULP DIVERGENCE, pinned to the port's value: the longitude reads -151.20929999999998 where ImageIO's Swift reader gave -151.2093 — one ULP apart, 1e-14 degrees, a nanometre on the ground. The two differ only in the order they fold degrees/minutes/seconds out of the EXIF rationals. The Rust host test compares GPS at 1e-9 and is indifferent; this file is byte-exact, so the number here is the port's.",
        ],
        "gps/lat_only.jpg": ["Both coordinates are required; a lone latitude yields nil/nil."],
        "gps/no_refs.jpg": ["Missing refs mean no negation — the values stay positive (northern/eastern)."],
        "gps/zero_and_lowercase_ref.jpg": [
            "LANDMINE, CONFIRMED: the ref comparison is case-SENSITIVE (`latRef == \"S\"` / `lonRef == \"W\"`). The raw lowercase refs \"s\"/\"w\" written here do NOT negate, so this southern/western point is reported as northern/eastern.",
            "exiftool normalises refs to uppercase on a normal write; these were planted with `#=` to bypass PrintConv, which is why the case matters at all.",
            "Latitude 0 comes out as +0. When the ref IS uppercase the same expression yields -0.0, which serialises as `-0` in JSON — see gps/south_west.jpg's sign handling and keep Rust's float formatting in mind.",
            "SUB-ULP DIVERGENCE, same cause as gps/south_west.jpg: the longitude reads 9.999999999999999e-05 where ImageIO gave 0.0001. One ULP.",
        ],

        // --- Embedded XMP ---------------------------------------------------
        "xmp/tagslist.jpg": ["Embedded digiKam:TagsList is read through CGImageMetadataCopyTags; rdf:Seq members arrive as nested CGImageMetadataTags, not strings."],
        "xmp/tag_sources_disagree.jpg": [
            "LANDMINE: only digiKam:TagsList is read. lr:hierarchicalSubject and dc:subject are invisible to the app even when they disagree.",
            "The tag match is on the LEAF NAME \"TagsList\", so any namespace declaring a TagsList would also be picked up.",
        ],
        "xmp/country_code.jpg": ["CountryCode is uppercased on read (\"it\" → \"IT\")."],
        "xmp/country_code_namespace_conflict.jpg": [
            "LANDMINE: CountryCode is matched by LEAF NAME only, so IPTC's Iptc4xmpCore:CountryCode competes with photo-tools:CountryCode.",
            "First tag enumerated wins (`countryCode == nil` guard). The order comes from ImageIO's XMP walk, not from the packet's byte order.",
        ],
        "xmp/regions_digikam_order.jpg": [
            "Embedded regions are recovered by re-serialising the packet with CGImageMetadataCreateXMPData and running the same string parser as the sidecar path.",
            "LANDMINE, CONFIRMED: ImageIO re-serialises struct fields ALPHABETICALLY, so Area always lands before Name — no matter how the packet was written.",
            "That means EVERY embedded MWG region in this app hits the backwards-Name off-by-one described on regions/exiftool_order.jpg. This file was written in digiKam order (Name first) and still comes back mis-named.",
            "Consequence for the port: embedded regions are currently shifted by one and the first is unnamed. The sidecar path is the only one that gets names right.",
        ],
        "xmp/regions_exiftool_order.jpg": [
            "Same regions as regions_digikam_order but written Area-before-Name. The output is IDENTICAL — proof that the input packet's element order is erased by ImageIO's re-serialisation.",
        ],
        "xmp/full_embedded.jpg": [
            "Tags + country + regions + EXIF date in one file, no sidecar.",
            "The single embedded region comes back with name = nil for the reason above, even though the packet names it \"Alice\".",
        ],

        // --- Sidecar merge --------------------------------------------------
        "sidecar/only.jpg": ["No embedded metadata: the sidecar supplies tags, country and regions."],
        "sidecar/conflict.jpg": [
            "The precedence table, all in one file:",
            "tags = UNION, embedded first; the case-insensitive dedup is first-wins, so the EMBEDDED spelling of a conflicting path survives (\"People/Alice\", not the sidecar's \"people/alice\").",
            "countryCode = EMBEDDED wins (IT, not FR).",
            "faceRegions = SIDECAR wins outright when non-empty — the embedded region is discarded, not merged.",
        ],
        "sidecar/no_regions.jpg": [
            "A sidecar with no regions leaves the embedded regions in place (the swap is guarded on non-empty).",
            "The surviving embedded region is unnamed — see xmp/regions_digikam_order.jpg for why.",
        ],
        "sidecar/tagslist_bag.jpg": ["rdf:Bag works exactly like rdf:Seq: the parser only scans for `<rdf:li>` between the TagsList open and close tags."],
        "sidecar/truncated_tagslist.jpg": ["No `</digiKam:TagsList>` means the whole block is skipped — a truncated sidecar silently yields zero tags rather than a partial list."],
        "sidecar/garbage.jpg": ["A non-XML sidecar parses to nothing; there is no error surface, the photo just looks untagged."],
        "sidecar/country_gap.jpg": ["Sidecar fills the country only when the embedded packet has none."],
        "sidecar/date_and_gps_ignored.jpg": [
            "LANDMINE: the sidecar parser reads exactly three things — digiKam:TagsList, photo-tools:CountryCode, MWG regions.",
            "exif:DateTimeOriginal and exif:GPS* in a sidecar are ignored entirely; dateTaken and GPS stay nil.",
        ],
        "sidecar/alt_prefix_country.jpg": ["Both \"photo-tools:CountryCode\" and \"phototools:CountryCode\" are probed, in that order."],
        "sidecar/tagslist_with_attributes.jpg": ["The open-tag probe is `<digiKam:TagsList>` first, then `<digiKam:TagsList ` (with the trailing space) for attribute-carrying forms."],
        "sidecar/empty_tag_entries.jpg": ["Empty and whitespace-only rdf:li entries are dropped; surviving values are whitespace-trimmed."],
        "sidecar/duplicate_case.jpg": [
            "Dedup key is `raw.lowercased()`, first occurrence wins — \"people/alice\" and \"PEOPLE/ALICE\" collapse into the first \"People/Alice\".",
            "\"People/Alice/Child\" is a different path and survives.",
        ],
        "sidecar/utf16.jpg": ["UTF-16 (BOM-prefixed) sidecars decode through the String(data:encoding:.utf16) fallback."],
        "sidecar/mwg_marker_no_areas.jpg": ["The \"mwg-rs present but no Areas parsed\" branch logs a warning and returns an empty region list."],

        // --- Region serialisation -------------------------------------------
        "regions/digikam_order.jpg": ["digiKam order (Name then Area) — the look-behind finds the correct name for every region."],
        "regions/exiftool_order.jpg": [
            "KNOWN BUG, PINNED AS-IS: exiftool serialises struct fields alphabetically, so Area precedes Name.",
            "`parseMWGRegions` locates each `<mwg-rs:Area>` and then searches BACKWARDS for the nearest mwg-rs:Name, which in this ordering is the PREVIOUS region's name.",
            "Result is an off-by-one: region 0 gets no name at all, region i gets region i-1's name, and the last name is lost.",
            "The Rust port must reproduce this. Fixing it is a separate, deliberate change with its own LibrarySnapshot version bump.",
        ],
        "regions/name_as_attribute.jpg": ["Attribute form `mwg-rs:Name=\"…\"` is tried before element form `<mwg-rs:Name>`."],
        "regions/element_form_area.jpg": ["Coordinates as child elements: the parser concatenates the open tag with everything up to `</mwg-rs:Area>` before running the field lookup."],
        "regions/unit_variants.jpg": [
            "stArea:unit=\"pixel\" is rejected; a missing unit is accepted; the comparison is `unit?.lowercased() == \"normalized\"`, so \"Normalized\" is accepted too.",
            "Rejected regions are skipped silently, they do not abort the walk.",
        ],
        "regions/name_beyond_lookback.jpg": ["The name look-behind window is 2000 characters. A name further back than that is not found and the region ends up unnamed."],
        "regions/malformed_last.jpg": ["An unterminated `<mwg-rs:Area` with nothing after it is skipped; earlier regions survive."],
        "regions/malformed_first.jpg": [
            "KNOWN BUG, PINNED AS-IS: an unterminated `<mwg-rs:Area` followed by a well-formed one finds the LATER `</mwg-rs:Area>`.",
            "The attribute blob then spans both regions, the coordinates come from the malformed (first) Area, and the second region is swallowed — one region out, not two.",
        ],
        "regions/non_numeric_coords.jpg": ["A coordinate that fails Double() drops that region only."],
        "regions/unnamed.jpg": ["A region with no mwg-rs:Name anywhere in the look-behind window is emitted with name = nil."],

        // --- Containers -----------------------------------------------------
        "containers/plain.png": ["PNG with no metadata: everything nil/empty."],
        "containers/png_with_xmp.png": ["XMP in a PNG iTXt chunk is read exactly like XMP in a JPEG APP1."],
        "containers/zero_byte.jpg": [
            "A zero-byte file yields no CGImageSource properties — but the sidecar is still read, so tags survive.",
            "The sidecar read is unconditional; it does not depend on the image opening.",
        ],
        "containers/truncated.jpg": ["Header-only JPEG: ImageIO opens the source but there are no usable properties."],
        "containers/actually_png.jpg": ["PNG bytes with a .jpg extension: ImageIO sniffs content, so the read succeeds anyway. Only the SCANNER cares about the extension."],
        "containers/actually_jpeg.txt": [
            "JPEG bytes with a .txt extension. `UTType(filenameExtension: \"txt\")` conforms to neither .image nor .movie, so the scanner never sees this file.",
            "The metadata reader would happily read it — this entry pins the reader, not the scanner.",
        ],
        "containers/heif_xmp.heic": [
            "HEIC whose XMP packet is an ITEM in the ISO-BMFF `meta` box, located through `iinf`/`iloc` — not a marker segment like JPEG's APP1 or PNG's iTXt.",
            "Before Phase 6 this file read as untagged: the container walk did not exist and `extract_xmp` fell through to None.",
            "The fixture carries no pixels. The metadata reader never decodes, and a real HEVC payload would cost more than the whole 2 MB fixture budget.",
        ],
        "containers/heif_exif.heic": [
            "HEIC with an Exif item and no XMP. This already worked before Phase 6 — kamadak-exif locates the Exif item itself — and the entry exists so that stays true.",
        ],
        "containers/heif_both.heic": [
            "Exif item first in `mdat`, XMP item second. Only `iloc` says where each starts, so a reader that assumed the packet was at the front of `mdat` would hand the TIFF block to the XMP parser.",
            "Both halves of a HEIC read at once: the date comes from kamadak-exif's own item walk, the tags and country from the core's.",
        ],
        "containers/heif_mif1_brand.heic": [
            "Identical content to heif_xmp.heic, written with `mif1` as the MAJOR brand and `heic` only in the compatible list — how libheif and several Android encoders write the same file.",
            "The brand check consults both, so which one an encoder picks is not something the reader depends on.",
        ],

        // --- Filenames ------------------------------------------------------
        "names/spaces and (parens).jpg": ["Spaces and parentheses in the name; sidecar lookup is `url.appendingPathExtension(\"xmp\")`, i.e. it operates on path components, not on a re-parsed string."],
        "names/emoji \u{1F335} cactus.jpg": ["Non-BMP characters in the filename (single scalar, so NFC/NFD is not a factor here — see stable_uuid_vectors.json for that)."],
        "names/UPPER.JPG": ["Uppercase extension. The scanner lowercases before UTType lookup; the sidecar manifest keys on the lowercased basename."],
        "names/dotted.name.v2.jpg": [
            "Multiple dots. The sidecar is `dotted.name.v2.jpg.xmp` (full basename + .xmp), NOT `dotted.name.v2.xmp`.",
            "`filename` in PhotoFile drops only the LAST extension, so it becomes \"dotted.name.v2\".",
        ],

        // --- Videos ---------------------------------------------------------
        "video/qt_utc.mov": ["QuickTime `moov/udta/©day` with an explicit +0000 offset."],
        "video/qt_offset.mov": ["Non-UTC offset is applied: 2018-06-15T14:33:07+0530 == 09:03:07Z."],
        "video/qt_naive.mov": [
            "LANDMINE: a zone-less ©day is read as UTC by AVFoundation, NOT as device-local — unlike EXIF dates, which are device-local.",
            "So the two date paths in this app disagree about what a zone-less timestamp means.",
        ],
        "video/qt_no_date.mov": ["No udta at all: AVAsset.creationDate is nil and the pipeline falls back to filesystem dates (see EarliestFilesystemDateTests)."],
        "video/qt_branded.mp4": ["A QuickTime-branded container with an .mp4 extension still resolves — AVFoundation dispatches on content, the scanner on extension."],
        "video/isom_udta.mp4": [
            "LANDMINE: an ISO-branded MP4 carrying the same `moov/udta/©day` reads as nil. AVFoundation only honours udta/©day for QuickTime-branded files.",
            "A Rust atom parser that reads udta/©day unconditionally would be MORE permissive than the Swift baseline — that is a behaviour change, not a bug fix.",
        ],
    ]

    // MARK: - The dump

    func testMetadataConformance() async throws {
        let assets = try ConformanceFixtures.assets()
        let files = try Self.assetFiles(under: assets)
        XCTAssertGreaterThanOrEqual(files.count, 50, "the asset tree looks truncated")

        var entries: [Entry] = []
        for relativePath in files {
            let url = assets.appendingPathComponent(relativePath)
            let ext = url.pathExtension.lowercased()
            let type = ext.isEmpty ? nil : UTType(filenameExtension: ext)
            let isImage = type?.conforms(to: .image) ?? false
            let isVideo = type?.conforms(to: .movie) ?? false
            let kind = isVideo ? "video" : (isImage ? "image" : "skipped")

            let metadata = readImageMetadata(path: url.path)
            // The bridge, exercised: the core hands back a zone-less wall
            // clock and the app resolves it in the device zone, which is what
            // `exifDateFormatter` did by having no `timeZone` at all.
            let captureDate = metadata.captureWallClock.flatMap(EnrichmentService.resolve)
            let videoDate = isVideo
                ? readVideoDate(path: url.path)
                    .map { Date(timeIntervalSince1970: TimeInterval($0)) }
                : nil

            entries.append(Entry(
                path: relativePath,
                scannerKind: kind,
                hasSidecar: FileManager.default.fileExists(
                    atPath: url.appendingPathExtension("xmp").path
                ),
                dateTaken: ConformanceDate.localWallClock(captureDate),
                countryCode: metadata.countryCode,
                gpsLatitude: metadata.gpsLatitude,
                gpsLongitude: metadata.gpsLongitude,
                hierarchicalTags: metadata.hierarchicalTags.map {
                    ConformanceTag(HierarchicalTag(fullPath: $0.fullPath, namespace: $0.namespace,
                                                   displayName: $0.displayName))
                },
                faceRegions: metadata.faceRegions.map {
                    ConformanceRegion(FaceRegion(name: $0.name, centerX: $0.centerX,
                                                 centerY: $0.centerY, width: $0.width,
                                                 height: $0.height))
                },
                videoDate: ConformanceDate.utc(videoDate),
                notes: Self.notes[relativePath] ?? []
            ))
        }

        try ConformanceFixtures.assertMatches(
            Dump(schema: 1, files: entries),
            fixture: "metadata_conformance.json"
        )
    }

    /// Every annotated path must exist, so a renamed asset can't leave its
    /// notes orphaned and silently unenforced.
    func testEveryAnnotatedPathExists() throws {
        let assets = try ConformanceFixtures.assets()
        let present = Set(try Self.assetFiles(under: assets))
        for path in Self.notes.keys.sorted() {
            XCTAssertTrue(present.contains(path), "annotated asset \(path) is missing from the tree")
        }
    }

    func testCommittedFixtureIsCanonical() throws {
        try ConformanceFixtures.assertCommittedBytesAreCanonical(
            Dump.self, fixture: "metadata_conformance.json"
        )
    }

    // MARK: - Enumeration

    /// Relative, `/`-separated paths of every asset that is *not* a sidecar,
    /// sorted. `.xmp` files are inputs to the merge, reported via `hasSidecar`.
    static func assetFiles(under root: URL) throws -> [String] {
        let fm = FileManager.default
        guard let walker = fm.enumerator(at: root, includingPropertiesForKeys: [.isRegularFileKey]) else {
            return []
        }
        var out: [String] = []
        let prefix = root.standardizedFileURL.path + "/"
        for case let url as URL in walker {
            let values = try url.resourceValues(forKeys: [.isRegularFileKey])
            guard values.isRegularFile == true else { continue }
            let name = url.lastPathComponent
            if name == ".DS_Store" { continue }
            if url.pathExtension.lowercased() == "xmp" { continue }
            let path = url.standardizedFileURL.path
            guard path.hasPrefix(prefix) else { continue }
            out.append(String(path.dropFirst(prefix.count)))
        }
        return out.sorted()
    }
}
